<img src="materials/images/introduction-to-r-programming-cover.png"/>


# 👋 Welcome, before you start
<br>

### 📚 Module overview

R is a statistical programming language that is very effective for computation and high-level graphics. It is commonly used for data analytics and data science.

We are going through five lessons in this module:

- [**Lesson 1: R Basic Data Types**](Lesson_1_R_Basic_Data_Types.ipynb)

- <font color=#E98300>**Lesson 2: R Data Structures**</font>    `📍You are here.`
    
- [**Lesson 3: Importing Data**](Lesson_3_Importing_Data.ipynb)

- [**Lesson 4: Conditionals and Loops**](Lesson_4_Conditionals_and_Loops.ipynb)

- [**Lesson 5: Functions**](Lesson_5_Functions.ipynb)

</br>

### ✅ Exercises
We encourage you to try the exercise questions in this module, and use the [**solutions to the exercises**](Exercise_solutions.ipynb) to help you study.

</br>

<div class="alert alert-block alert-info">
<h3>⌨️ Keyboard shortcut</h3>

These common shortcut could save your time going through this notebook:
- Run the current cell: **`Enter + Shift`**.
- Add a cell above the current cell: Press **`A`**.
- Add a cell below the current cell: Press **`B`**.
- Change a code cell to markdown cell: Select the cell, and then press **`M`**.
- Delete a cell: Press **`D`** twice.

Need more help with keyboard shortcut? Press **`H`** to look it up.
</div>

---

# Lesson 2: R Data Structures

A data structure is a format or object for storing data. We are going to go through these concepts:

- [Vectors](#Vectors)
- [Lists](#Lists)
- [Matrix](#Matrix)
- [Data Frame](#Data-Frame)

`🕒 This module should take about 40 minutes to complete.`

`✍️ This notebook is written using R.`

## Vectors
The fundamental data structure in R is the vector. A vector is a one-dimensional sequence of data elements, of the same type, stored in a sequence. The elements are most commonly of type character, logical, integer or numeric.

A common way to create a vector is by directly specifying its content. The c() function can be used to "combine" the specified values:

In [1]:
v1  <-  c(1,2,3,4)
v1

[1] 1 2 3 4

In [2]:
v2 <- c("This", "is", "absolutely", "fantastic")
v2

[1] "This"       "is"         "absolutely" "fantastic"

In [3]:
v3  <-  c(TRUE, FALSE, TRUE, FALSE)
print(v3)

[1]  TRUE FALSE  TRUE FALSE


**Note that if you mix data types, R will coerce the vector to a single data type:**

In [4]:
v4  <-  c(TRUE, FALSE, TRUE, "FALSE")
print(v4)

[1] "TRUE"  "FALSE" "TRUE"  "FALSE"


<div class="alert alert-block alert-warning">
<b>Alert:</b> A vector is a data structure that contains only a single data type (e.g., integers, logicals).
</div>

### Creating Vectors from a Sequence of Numbers

A vector can be constructed from  a sequence of numbers:

In [5]:
# Create a vector from the sequence of numbers 1 through 10 (inclusive):

seq1 <- 1:10
print(seq1)

 [1]  1  2  3  4  5  6  7  8  9 10


In [6]:
# Create a vector of numbers beginning from 5 and counting down through (and including) -5:

seq1 <- 5:-5
print(seq1)

 [1]  5  4  3  2  1  0 -1 -2 -3 -4 -5


### A Vector Created using the seq() Function

The seq() ("sequence") function can be used to construct a vector from a sequence of numbers:

In [7]:
# Create a vector of 10 numbers beginning from 1:

seq(10)

[1]  1  2  3  4  5  6  7  8  9 10

In [8]:
# Create a vector of numbers from 1 through 10, but skipping every second number:

seq(1, 10, 2)

[1] 1 3 5 7 9

In [9]:
# Create a vector of 20 numbers, evenly spaced between the numbers 1 through 10:

seq(1, 10, length=20)

[1]  1.000000  1.473684  1.947368  2.421053  2.894737  3.368421  3.842105
 [8]  4.315789  4.789474  5.263158  5.736842  6.210526  6.684211  7.157895
[15]  7.631579  8.105263  8.578947  9.052632  9.526316 10.000000

In [10]:
# Create a vector of numbers from 1 through 10, stepping every 0.1:

seq(from = 1, to = 10, by = 0.1)

[1]  1.0  1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.0  2.1  2.2  2.3  2.4
[16]  2.5  2.6  2.7  2.8  2.9  3.0  3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9
[31]  4.0  4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.0  5.1  5.2  5.3  5.4
[46]  5.5  5.6  5.7  5.8  5.9  6.0  6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
[61]  7.0  7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.0  8.1  8.2  8.3  8.4
[76]  8.5  8.6  8.7  8.8  8.9  9.0  9.1  9.2  9.3  9.4  9.5  9.6  9.7  9.8  9.9
[91] 10.0

### A Vector Created from a Sample of Numbers

In [11]:
# Create a vector by drawing from a sample of numbers from 1 through 10, without replacement:

sample(1:10)

[1] 10  5  3  1  6  4  9  7  8  2

### Examining Vectors

#### typeof()
The typeof() function can be used to evaluate the data type that a vector contains:

In [12]:
# Mixed data types coerced to a single data type:

v4  <-  c(TRUE, FALSE, TRUE, "FALSE")

typeof(v4)

[1] "character"

#### length()
The length() function can be used to determine the number of elements that a vector contains:

In [13]:
length(v4)

[1] 4

### Missing Data

Missing values in R are indicated by NA (Not Available):

In [14]:
x <- c(0.5, 0.7, NA)

# Variable containing a vector with a misssing value
x

[1] 0.5 0.7  NA

In [15]:
# Try this.

x <- c("a", NA, "c", "d", "e")

# Variable containing a vector with a misssing value
x

[1] "a" NA  "c" "d" "e"

#### is.na() 
is.na() can be used to test whether a value is missing. It returns a logical vector:

In [16]:
# Test each value in a vector as to whether it is missing or not:

x <- c("a", NA, "c", "d", "e")

# x is the variable containing a vector with a missing value
is.na(x)

[1] FALSE  TRUE FALSE FALSE FALSE

#### anyNA() 
anyNA() can be used to evaluate whether a vector contains any missing (NA) values:

In [17]:
x <- c("a", NA, "c", "d", "e")

# x is the variable containing a vector with a misssing value
anyNA(x)

[1] TRUE

### Universal (built-in) functions that can be applied to vectors

In [18]:
# Create a vector "v":

v = c(25, 9, 16, 4)
v

[1] 25  9 16  4

In [19]:
# Return the mean value of the vector

mean(v)

[1] 13.5

In [20]:
# Return the square root of each value in the vector

sqrt(v)

[1] 5 3 4 2

In [21]:
# Return the maximum value in the vector

max(v)

[1] 25

In [22]:
# Return the smallest value in the vector

min(v)

[1] 4

In [23]:
# Return the sum of the values in the vector

sum(v)

[1] 54

In [24]:
# Sort the values in a vector in ascending order

sort(v)

[1]  4  9 16 25

In [25]:
# Sort the values in a vector in descending order

sort(v, decreasing=TRUE)

[1] 25 16  9  4

In [26]:
# Count the frequency of occurrence for each element in a vector:

table(c(20,30,50,20,40,10,40,20))


10 20 30 40 50 
 1  3  1  2  1 

### Functions for logical vectors

In [27]:
# Test each value in the vector v as to whether it is greater than 10 or not (returns TRUE or FALSE):

v = c(25, 9, 16, 4)

v > 10

[1]  TRUE FALSE  TRUE FALSE

In [28]:
# any() returns TRUE if any of the logicals are TRUE:

any(v > 10)

[1] TRUE

In [29]:
# all() returns TRUE if all of the logicals are TRUE:

all(v > 10)

[1] FALSE

In [30]:
# which() returns the indices/locations of the TRUE values (interpreted as as "Which index positions are TRUE?"):

which(v > 10)

[1] 1 3

<div class="alert alert-block alert-warning">
<b>Alert:</b> The index positions of a vector in R begin counting from 1. 
</div>

In [31]:
# sum() returns the number of logicals that are TRUE:

sum(v > 10)

[1] 2

### Vector Subsetting
The index position of the items within a vector begin counting from 1. You can get slices or subsets of a vector by placing the index position of items between square brackets:

In [32]:
# Create a vector named "items":

items <- c(5,10,15,20,25,30,35,40)
items

[1]  5 10 15 20 25 30 35 40

In [33]:
# Return the first element in the vector; the element at index position 1:

items[1]

[1] 5

In [34]:
# Return a vector containing the third element:

items[3]

[1] 15

In [35]:
# A negative value means to exclude the index position.
# Return a vector with everything except the third element:

items[-3]

[1]  5 10 20 25 30 35 40

In [36]:
# Return a vector with the first through second elements (inclusive):

items[1:2]

[1]  5 10

In [37]:
# You can use a vector to do the subsetting (particularly when the indices are non-consecutive).
# Return a vector with the first and fourth elements:
                                                         
items[c(1,4)]                                                     

[1]  5 20

In [38]:
# Return a vector with the first, third, and first element again:

items[c(1,3,1)]

[1]  5 15  5

In [39]:
# Return a vector without the first through second elements:

items[-1:-2]

[1] 15 20 25 30 35 40

### Vector Assignment

In [40]:
# Create a vector named "items":

items <- c(5,10,15,20,25,30,35,40)
items

[1]  5 10 15 20 25 30 35 40

In [41]:
# Assign 100 to the item at index position 2:

items[2] <- 100
items

[1]   5 100  15  20  25  30  35  40

In [42]:
# Assign 0 to every index position except 2:

items[-2] <- 0
items

[1]   0 100   0   0   0   0   0   0

### Vectorized Operations
A vectorized operation applies an operation to a vector element-wise: 

In [43]:
# Create a vector named "items":

items <- c(5,10,15,20,25,30,35,40)
items

[1]  5 10 15 20 25 30 35 40

In [44]:
# Divide each item in a vector by 5, and return a new vector containing the result

items/5

[1] 1 2 3 4 5 6 7 8

In [45]:
# Multiply two vectors together (element-wise).  Return a new vector with the results:

c(1,2,3) * c(2,4,6)

[1]  2  8 18

### ✅ Exercise 4

- Create a vector of numbers from 1-12. 
- Square the vector, returning a new vector containing the square of each number from the original vector.

In [46]:
# Create a vector from 1 to 12
numbers <- 1:12

# Square each number in the vector
squared_numbers <- numbers^2

# Print the squared vector
print(squared_numbers)

 [1]   1   4   9  16  25  36  49  64  81 100 121 144


---

### Using Logicals to Perform Compound Operations on Vectors
A compound operation is when you test two or more conditions for whether a value in a vector returns TRUE:

In [47]:
# & is the "AND" operation in R.
# Return TRUE where each item at a given index position between the vectors is TRUE:

c(FALSE, TRUE, FALSE) & c(TRUE, TRUE, TRUE)

[1] FALSE  TRUE FALSE

In [48]:
# | is the "OR" operation in R.
# Return TRUE where either item at a given index position between the vectors is TRUE:

c(FALSE, TRUE, FALSE) | c(TRUE, TRUE, TRUE)

[1] TRUE TRUE TRUE

In [49]:
# Create the vector "v":

v = c(25, 9, 16, 4)

# Test whether a value in the vector v is either less than 5 or (|) greater than 20:
(v < 5) | (v > 20)

[1]  TRUE FALSE FALSE  TRUE

In [50]:
# Place the logical operation from above between the square brackets of "v" to return the actual values.
# In otherwords, v will return any value whose index position is TRUE:

v[(v < 5) | (v > 20)]

[1] 25  4

<div class="alert alert-block alert-info">
<b>Tip:</b> The use of logical (conditional) operations will become very useful when you desire to explore and analyze your data.
</div>

### ✅ Exercise 5

- Create a vector named "nums" containing numbers from 1 through 10. 
- Within the square brackets of "nums", perform a compound operation so that only values that are either less than 4 or greater than 8 are returned.

In [51]:
# Create a vector containing numbers from 1 to 10
nums <- 1:10

# Filter values that are either less than 4 or greater than 8
filtered_nums <- nums[nums < 4 | nums > 8]

# Print the result
print(filtered_nums)

[1]  1  2  3  9 10


---

### Naming Vectors
If desired, you can use key/value pairs to assign a name to each element within a vector. You can then use the element's name to access its value:

In [52]:
# Create a vector giving names to each element:

groceries <- c("milk"=3.56, "bread"=4.29, "rice"=5.98)
groceries

milk bread  rice 
 3.56  4.29  5.98

In [53]:
# Place the element's name within the square brackets of the vector to return its value:

groceries["rice"]

rice 
5.98

In [54]:
# Use a vector of names to return more than one element's value:

groceries[c("rice", "bread")]

rice bread 
 5.98  4.29

---

## Lists
A list is a collection of items but unlike vectors, lists can contain any mixture of elements of any type. Lists can even contain other lists.

You can use the **list()** function to crerate a list:

In [55]:
L <- list("a", 1, 2.5, TRUE)
L

[[1]]
[1] "a"

[[2]]
[1] 1

[[3]]
[1] 2.5

[[4]]
[1] TRUE

Elements within a list can be accessed by placing the element's index position within square brackets:

In [56]:
L[4]

[[1]]
[1] TRUE

In [57]:
L[2:3]

[[1]]
[1] 1

[[2]]
[1] 2.5

#### Named lists
Lists can also use names by creating key/value pairs to assign a name to each element within the list. You can then access an element within the list by using the element's name/key:

In [58]:
a_list <- list("San Francisco"= 1, "Santa Clara" = 2, "San Jose" = 3)
a_list

$`San Francisco`
[1] 1

$`Santa Clara`
[1] 2

$`San Jose`
[1] 3

<div class="alert alert-block alert-success">
<b>Note:</b> The '$' preceding the characters in the output above indicates that the characters are a key from the named list as opposed to a value.
</div>

In [59]:
a_list["San Jose"]

$`San Jose`
[1] 3

---

## Matrix
A matrix is a two-dimensional collection of data elements. Like vectors, matrices can only contain a single data type. You can create a matrix by using the **matrix( )** function. 

To create a matrix, you first specify a vector and then you can specify the desired dimensions (rows x cols).

In [60]:
matrix(1:12, nrow=3, ncol=4)

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

Alternatively, after specifying a vector, you can indicate the desired number of rows and the number of columns will be calculated.

In [61]:
matrix(c(1:12), nrow = 3)

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

Alternatively, after specifying a vector, you can indicate the desired number of columns and the number of rows will be calculated.

In [62]:
matrix(c(1:12), ncol = 2)

[,1] [,2]
[1,] 1     7  
[2,] 2     8  
[3,] 3     9  
[4,] 4    10  
[5,] 5    11  
[6,] 6    12

#### rbind( )
The rbind() function is used to bind vectors into a matrix (row-wise):

In [63]:
rbind(c(1,2,3), c(4,5,6))

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

#### cbind( )
The cbind() function is used to bind vectors into a matrix (column-wise):

In [64]:
cbind(c(1,2,3), c(4,5,6))

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

#### dim( )
The dim() function will return the dimensions (rows, cols) of a matrix:

In [65]:
nums <- matrix(1:12, 3, 4)

dim(nums)

[1] 3 4

#### nrow( )
The nrow() function will return the number of rows in a matrix:

In [66]:
nums <- matrix(1:12, 3, 4)

nrow(nums)

[1] 3

#### ncol( )
The ncol() function will return the number of columns in a matrix:

In [67]:
nums <- matrix(1:12, 3, 4)

ncol(nums)

[1] 4

### Matrix Subsetting
You can select a subset of a matrix by placing the desired rows and columns, separated by a comma, within square brackets.

In [68]:
# Create a matrix named "nums":

nums <- matrix(1:12, 3, 4)
nums

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [69]:
# Return the element located in the second row of the third column:

nums[2,3]

[1] 8

In [70]:
# Return rows 1 and 2 of columns 3 and 4:

nums[1:2, 3:4]

[,1] [,2]
[1,] 7    10  
[2,] 8    11

In [71]:
# An alternative way to get the same results as above...
# Return all rows except the third, and all columns except the first and second:

nums[-3, -1:-2]

[,1] [,2]
[1,] 7    10  
[2,] 8    11

In [72]:
# Return just row two (must be followed by a comma) and all of the columns:

nums[2, ]

[1]  2  5  8 11

In [73]:
# Return just column four (must be preceded by a comma) and all of the rows:

nums[, 4]

[1] 10 11 12

#### colnames()
The colnames() function can be used to assign names to the columns:

In [74]:
colnames(nums) <- c("col1", "col2", "col3", "col4")
nums

col1 col2 col3 col4
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

#### rownames()
The rownames() function can be used to assign names to the rows:

In [75]:
rownames(nums) <- c("row1", "row2", "row3")
nums

col1 col2 col3 col4
row1 1    4    7    10  
row2 2    5    8    11  
row3 3    6    9    12

### ✅ Exercise 6

Create a matrix by passing it a vector with numbers from 21 to 40. Shape the matrix to have 4 rows and 5 columns. Assign the names of the weekdays (i.e., Monday through Friday) to the five columns. Name the four rows "California", "Texas", "Florida", "New York". Name the matrix "states". Display the matrix.

In [76]:
# Create a vector with numbers from 21 to 40
values <- 21:40

# Create a matrix with 4 rows and 5 columns
states <- matrix(values, nrow = 4, ncol = 5)

# Assign column names (weekdays)
colnames(states) <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")

# Assign row names (states)
rownames(states) <- c("California", "Texas", "Florida", "New York")

# Display the matrix
print(states)

           Monday Tuesday Wednesday Thursday Friday
California     21      25        29       33     37
Texas          22      26        30       34     38
Florida        23      27        31       35     39
New York       24      28        32       36     40


---

### Subsetting Named Matrixes

In [77]:
# Create a matrix with named rows and columns:

nums <- matrix(1:12, 3, 4)
colnames(nums) <- c("col1", "col2", "col3", "col4")
rownames(nums) <- c("row1", "row2", "row3")

nums

col1 col2 col3 col4
row1 1    4    7    10  
row2 2    5    8    11  
row3 3    6    9    12

#### Use the row/col names to subset the matrix:

In [78]:
# Return "row1" and every column:

print(nums["row1",])

col1 col2 col3 col4 
   1    4    7   10 


In [79]:
# Return all rows and just "col2" and "col4":

nums[, c("col2","col4")]

col2 col4
row1 4    10  
row2 5    11  
row3 6    12

In [80]:
# Return "row2" and "row3" of "col1" and "col4":

nums[c("row2", "row3"), c("col1","col4")]

col1 col4
row2 2    11  
row3 3    12

---

## Data Frames
Data frames are the most common way of storing and analyzing data in R. The columns (which are vectors) can be of different types, but they must be the same length.

You can think of a data frame as a collection of vectors that all must be the same length.

In [81]:
df <- data.frame(name=c("Carl","Diane","Sally","Ben","Kimmy"),
                 age=c(42,40,17,14,12),
                 sex=c("Male","Female","Female","Male","Female"))

df

name  age sex   
1 Carl  42  Male  
2 Diane 40  Female
3 Sally 17  Female
4 Ben   14  Male  
5 Kimmy 12  Female

#### dim()
The dim() function is used to get the dimensions (rows x cols) of a data frame:

In [82]:
dim(df)

[1] 5 3

#### nrow()
The nrow() function is used to get the number of rows in a data frame:

In [83]:
nrow(df)

[1] 5

#### ncol()
The ncol() function is used to get the number of columns in a data frame:

In [84]:
ncol(df)

[1] 3

#### colnames()
The colnames() function is used to get the column names of a data frame:

In [85]:
colnames(df)

[1] "name" "age"  "sex"

### Data Frame Subsetting
You can select a subset of a data frame by placing the desired rows and columns, separated by a comma, within square brackets. You can use either an index position or a name. 

In [86]:
# Create a data frame:

df <- data.frame(name=c("Carl","Diane","Sally","Ben","Kimmy"),
                 age=c(42,40,17,14,12),
                 sex=c("Male","Female","Female","Male","Female"))

df

name  age sex   
1 Carl  42  Male  
2 Diane 40  Female
3 Sally 17  Female
4 Ben   14  Male  
5 Kimmy 12  Female

#### Subsets of rows

In [87]:
# Return the first two rows with all of the columns:

df[1:2, ]

name  age sex   
1 Carl  42  Male  
2 Diane 40  Female

In [88]:
# Return the first and third row (with all of the columns); a comma follows the vector so it indicates rows):

df[c(1,3), ]

name  age sex   
1 Carl  42  Male  
3 Sally 17  Female

#### Subsets of columns

In [89]:
# Return the first and third columns (with all of the rows); no comma follows the vector so it indicates columns:

df[c(1, 3)] 

name  sex   
1 Carl  Male  
2 Diane Female
3 Sally Female
4 Ben   Male  
5 Kimmy Female

<div class="alert alert-block alert-warning">
<b>Alert:</b> To subset a data frame, placing a vector within square brackets, not followed by a comma, indicates the desired columns that you would like returned. If the vector is followed by a comma, this indicates that these are the rows that you would like returned.</div>

In [90]:
# Return the column named "name" with all of the rows (returns a data frame):

df["name"]

name 
1 Carl 
2 Diane
3 Sally
4 Ben  
5 Kimmy

In [91]:
# Return the column named "name" with all of the rows (using "$" returns the vector):

df$name

[1] "Carl"  "Diane" "Sally" "Ben"   "Kimmy"

In [92]:
# Using a vector for the names of the columns returns those columns in the selected order (with all of the rows):

df[c("sex", "age", "name")] 

sex    age name 
1 Male   42  Carl 
2 Female 40  Diane
3 Female 17  Sally
4 Male   14  Ben  
5 Female 12  Kimmy

#### Row and Column subsetting

In [93]:
# Return the first two rows of the first two columns:

df[1:2, 1:2]

name  age
1 Carl  42 
2 Diane 40

In [94]:
# Return the first two rows of the columns named "name" and "age":

df[1:2, c("name", "age")]

name  age
1 Carl  42 
2 Diane 40

In [95]:
# Another way to return the same values as above.
# Return all rows except the third through the fifth, and all columns except the third one:

df[-3:-5, -3]

name  age
1 Carl  42 
2 Diane 40

#### Logical subsetting
A logical expression is a question and can only return TRUE or FALSE.

In [96]:
# Here, you are asking each value in the column "age" if it is less than 18:

df$age < 18

[1] FALSE FALSE  TRUE  TRUE  TRUE

In [97]:
# By placing the logical expression from above within the square brackets of the data frame, 
# only the TRUE rows will be returned.


# Return the rows where the column "age" is less than 18, and return the columns "age" and "name": 

df[df$age < 18, c("age", "name")]

age name 
3 17  Sally
4 14  Ben  
5 12  Kimmy

<div class="alert alert-block alert-success">
<b>Note:</b> A logical expression can only return TRUE or FALSE. By placing a logical expression within the square brackets following a data frame, only the rows that are TRUE will be returned. Using logical expressions is primarily how you will explore and wrangle your data.
</div>

#### Compound operation

In [98]:
# Here, you are asking the data frame which rows have an "age" less than 18 AND a "sex" equivalent to "Female":
(df$age<18) & (df$sex=="Female")

[1] FALSE FALSE  TRUE FALSE  TRUE

In [99]:
# By placing the logical expression from above between the square brackets of the data frame,
# you will return the rows where "age" is less than 18 AND "sex" is "Female", and all of the columns: 

df <- data.frame(name=c("Carl","Diane","Sally","Ben","Kimmy"),
                 age=c(42,40,17,14,12),
                 sex=c("Male","Female","Female","Male","Female"))

df[(df$age<18) & (df$sex=="Female"), ]

name  age sex   
3 Sally 17  Female
5 Kimmy 12  Female

### ✅ Exercise 7

From the following data frame, select only the rows where "age" is over 30 and "sex" is "Male", and return only the columns "age" and "sex".

In [100]:
df[(df$age > 30) & (df$sex =="Male"), c("age", "sex")]

age sex 
1 42  Male

---

# 🌟 Ready for the next one?
<br>

- [**Lesson 3: Importing Data**](Lesson_3_Importing_Data.ipynb)

- [**Lesson 4: Conditionals and Loops**](Lesson_4_Conditionals_and_Loops.ipynb)

- [**Lesson 5: Functions**](Lesson_5_Functions.ipynb)

---

# Contributions & acknowledgment

Thanks Antony Ross for contributing the content for this notebook.

---

Copyright (c) 2022 Stanford Data Ocean (SDO)

All rights reserved.